on:
  push:
    branches: ['**']   # corre em todos os branches
  pull_request:
    branches: ['**']
  workflow_dispatch: {}   # permite arrancar manualmente no separador Actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://download.pytorch.org/whl/cpu \
            torch==2.3.* torchvision==0.18.* torchaudio==2.3.*
          pip install pytest numpy pillow opencv-python-headless albumentations

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings